/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Noggog;
using Noggog.Notifying;
using BethesdaGitSync.Internals;
using ReactiveUI;
using DynamicData;
using CSharpExt.Rx;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;
using Loqui.Internal;
using System.Diagnostics;
using System.Collections.Specialized;

namespace BethesdaGitSync
{
    #region Class
    public partial class Grouping : 
        LoquiNotifyingObject,
        IGrouping,
        ILoquiObject<Grouping>,
        ILoquiObjectSetter,
        IEquatable<Grouping>
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => Grouping_Registration.Instance;
        public static Grouping_Registration Registration => Grouping_Registration.Instance;

        #region Ctor
        public Grouping()
        {
            _hasBeenSetTracker = new BitArray(((ILoquiObject)this).Registration.FieldCount);
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region Nickname
        private String _Nickname;
        public String Nickname
        {
            get => this._Nickname;
            set => this.RaiseAndSetIfReferenceChanged(ref this._Nickname, value, nameof(Nickname));
        }
        #endregion
        #region Mappings
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private readonly SourceSetList<Mapping> _Mappings = new SourceSetList<Mapping>();
        public ISourceSetList<Mapping> Mappings => _Mappings;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        public IEnumerable<Mapping> MappingsEnumerable
        {
            get => _Mappings.Items;
            set => _Mappings.SetTo(value);
        }
        #region Interface Members
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ISourceSetList<Mapping> IGrouping.Mappings => _Mappings;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IObservableSetList<Mapping> IGroupingGetter.Mappings => _Mappings;
        #endregion

        #endregion

        IMask<bool> IEqualsMask<Grouping>.GetEqualsMask(Grouping rhs, EqualsMaskHelper.Include include) => GroupingCommon.GetEqualsMask(this, rhs, include);
        IMask<bool> IEqualsMask<IGroupingGetter>.GetEqualsMask(IGroupingGetter rhs, EqualsMaskHelper.Include include) => GroupingCommon.GetEqualsMask(this, rhs, include);
        #region To String
        public string ToString(
            string name = null,
            Grouping_Mask<bool> printMask = null)
        {
            return GroupingCommon.ToString(this, name: name, printMask: printMask);
        }

        public void ToString(
            FileGeneration fg,
            string name = null)
        {
            GroupingCommon.ToString(this, fg, name: name, printMask: null);
        }

        #endregion

        IMask<bool> ILoquiObjectGetter.GetHasBeenSetMask() => this.GetHasBeenSetMask();
        public Grouping_Mask<bool> GetHasBeenSetMask()
        {
            return GroupingCommon.GetHasBeenSetMask(this);
        }
        #region Equals and Hash
        public override bool Equals(object obj)
        {
            if (!(obj is Grouping rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Grouping rhs)
        {
            if (rhs == null) return false;
            if (!string.Equals(this.Nickname, rhs.Nickname)) return false;
            if (!this.Mappings.SequenceEqual(rhs.Mappings)) return false;
            return true;
        }

        public override int GetHashCode()
        {
            int ret = 0;
            ret = HashHelper.GetHashCode(Nickname).CombineHashCode(ret);
            ret = HashHelper.GetHashCode(Mappings).CombineHashCode(ret);
            return ret;
        }

        #endregion


        #region Xml Translation
        #region Xml Create
        [DebuggerStepThrough]
        public static Grouping Create_Xml(
            XElement node,
            MissingCreate missing = MissingCreate.New,
            Grouping_TranslationMask translationMask = null)
        {
            return Create_Xml(
                missing: missing,
                node: node,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        [DebuggerStepThrough]
        public static Grouping Create_Xml(
            XElement node,
            out Grouping_ErrorMask errorMask,
            bool doMasks = true,
            Grouping_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            var ret = Create_Xml(
                missing: missing,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask.GetCrystal());
            errorMask = Grouping_ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }

        public static Grouping Create_Xml(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            MissingCreate missing = MissingCreate.New)
        {
            switch (missing)
            {
                case MissingCreate.New:
                case MissingCreate.Null:
                    if (node == null) return missing == MissingCreate.New ? new Grouping() : null;
                    break;
                default:
                    break;
            }
            var ret = new Grouping();
            try
            {
                foreach (var elem in node.Elements())
                {
                    GroupingCommon.FillPublicElement_Xml(
                        item: ret,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            return ret;
        }

        public static Grouping Create_Xml(
            string path,
            MissingCreate missing = MissingCreate.New,
            Grouping_TranslationMask translationMask = null)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            return Create_Xml(
                missing: missing,
                node: node,
                translationMask: translationMask);
        }

        public static Grouping Create_Xml(
            string path,
            out Grouping_ErrorMask errorMask,
            Grouping_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            return Create_Xml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static Grouping Create_Xml(
            string path,
            ErrorMaskBuilder errorMask,
            Grouping_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            return Create_Xml(
                missing: missing,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        public static Grouping Create_Xml(
            Stream stream,
            MissingCreate missing = MissingCreate.New,
            Grouping_TranslationMask translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            return Create_Xml(
                missing: missing,
                node: node,
                translationMask: translationMask);
        }

        public static Grouping Create_Xml(
            Stream stream,
            out Grouping_ErrorMask errorMask,
            Grouping_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = XDocument.Load(stream).Root;
            return Create_Xml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static Grouping Create_Xml(
            Stream stream,
            ErrorMaskBuilder errorMask,
            Grouping_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New)
        {
            var node = XDocument.Load(stream).Root;
            return Create_Xml(
                missing: missing,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        #endregion

        #region Xml Copy In
        public void CopyIn_Xml(
            XElement node,
            MissingCreate missing = MissingCreate.New)
        {
            CopyIn_Xml_Internal(
                missing: missing,
                node: node,
                errorMask: null,
                translationMask: null);
        }

        public virtual void CopyIn_Xml(
            XElement node,
            out Grouping_ErrorMask errorMask,
            Grouping_TranslationMask translationMask = null,
            MissingCreate missing = MissingCreate.New,
            bool doMasks = true)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            CopyIn_Xml_Internal(
                missing: missing,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Grouping_ErrorMask.Factory(errorMaskBuilder);
        }

        protected void CopyIn_Xml_Internal(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            MissingCreate missing = MissingCreate.New)
        {
            LoquiXmlTranslation<Grouping>.Instance.CopyIn(
                missing: missing,
                node: node,
                item: this,
                skipProtected: true,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public void CopyIn_Xml(
            string path,
            MissingCreate missing = MissingCreate.New)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            this.CopyIn_Xml(
                missing: missing,
                node: node);
        }

        public void CopyIn_Xml(
            string path,
            out Grouping_ErrorMask errorMask,
            Grouping_TranslationMask translationMask,
            MissingCreate missing = MissingCreate.New,
            bool doMasks = true)
        {
            var node = System.IO.File.Exists(path) ? XDocument.Load(path).Root : null;
            this.CopyIn_Xml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask,
                doMasks: doMasks);
        }

        public void CopyIn_Xml(
            Stream stream,
            MissingCreate missing = MissingCreate.New)
        {
            var node = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                missing: missing,
                node: node);
        }

        public void CopyIn_Xml(
            Stream stream,
            out Grouping_ErrorMask errorMask,
            Grouping_TranslationMask translationMask,
            MissingCreate missing = MissingCreate.New,
            bool doMasks = true)
        {
            var node = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                missing: missing,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask,
                doMasks: doMasks);
        }

        #endregion

        #region Xml Write
        public virtual void Write_Xml(
            XElement node,
            out Grouping_ErrorMask errorMask,
            bool doMasks = true,
            Grouping_TranslationMask translationMask = null,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            this.Write_Xml(
                name: name,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Grouping_ErrorMask.Factory(errorMaskBuilder);
        }

        public virtual void Write_Xml(
            string path,
            out Grouping_ErrorMask errorMask,
            Grouping_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }

        public void Write_Xml(
            string path,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }
        public virtual void Write_Xml(
            Stream stream,
            out Grouping_ErrorMask errorMask,
            Grouping_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }

        public void Write_Xml(
            Stream stream,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }
        public void Write_Xml(
            XElement node,
            string name = null,
            Grouping_TranslationMask translationMask = null)
        {
            this.Write_Xml(
                name: name,
                node: node,
                errorMask: null,
                translationMask: translationMask.GetCrystal());
        }

        public void Write_Xml(
            string path,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().SaveIfChanged(path);
        }

        public void Write_Xml(
            Stream stream,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().Save(stream);
        }

        public void Write_Xml(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            GroupingCommon.Write_Xml(
                item: this,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }
        #endregion

        #endregion

        protected readonly BitArray _hasBeenSetTracker;
        protected bool GetHasBeenSet(int index)
        {
            switch ((Grouping_FieldIndex)index)
            {
                case Grouping_FieldIndex.Nickname:
                case Grouping_FieldIndex.Mappings:
                    return true;
                default:
                    throw new ArgumentException($"Unknown field index: {index}");
            }
        }

        public Grouping Copy(
            Grouping_CopyMask copyMask = null,
            IGroupingGetter def = null)
        {
            return Grouping.Copy(
                this,
                copyMask: copyMask,
                def: def);
        }

        public static Grouping Copy(
            IGrouping item,
            Grouping_CopyMask copyMask = null,
            IGroupingGetter def = null)
        {
            Grouping ret;
            if (item.GetType().Equals(typeof(Grouping)))
            {
                ret = new Grouping();
            }
            else
            {
                ret = (Grouping)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public static Grouping Copy_ToLoqui(
            IGroupingGetter item,
            Grouping_CopyMask copyMask = null,
            IGroupingGetter def = null)
        {
            Grouping ret;
            if (item.GetType().Equals(typeof(Grouping)))
            {
                ret = new Grouping() as Grouping;
            }
            else
            {
                ret = (Grouping)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public void CopyFieldsFrom(IGroupingGetter rhs)
        {
            this.CopyFieldsFrom(
                rhs: (IGroupingGetter)rhs,
                def: null,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: null);
        }

        public void CopyFieldsFrom(
            IGroupingGetter rhs,
            Grouping_CopyMask copyMask,
            IGroupingGetter def = null)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: def,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: copyMask);
        }

        public void CopyFieldsFrom(
            IGroupingGetter rhs,
            out Grouping_ErrorMask errorMask,
            Grouping_CopyMask copyMask = null,
            IGroupingGetter def = null,
            bool doMasks = true)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            GroupingCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMaskBuilder,
                copyMask: copyMask);
            errorMask = Grouping_ErrorMask.Factory(errorMaskBuilder);
        }

        public void CopyFieldsFrom(
            IGroupingGetter rhs,
            ErrorMaskBuilder errorMask,
            Grouping_CopyMask copyMask = null,
            IGroupingGetter def = null,
            bool doMasks = true)
        {
            GroupingCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMask,
                copyMask: copyMask);
        }

        protected void SetNthObject(ushort index, object obj)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                    this.Nickname = (String)obj;
                    break;
                case Grouping_FieldIndex.Mappings:
                    this._Mappings.SetTo((IEnumerable<Mapping>)obj);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        partial void ClearPartial();

        protected void CallClearPartial_Internal()
        {
            ClearPartial();
        }

        public void Clear()
        {
            CallClearPartial_Internal();
            GroupingCommon.Clear(this);
        }


        public static Grouping Create(IEnumerable<KeyValuePair<ushort, object>> fields)
        {
            var ret = new Grouping();
            foreach (var pair in fields)
            {
                CopyInInternal_Grouping(ret, pair);
            }
            return ret;
        }

        protected static void CopyInInternal_Grouping(Grouping obj, KeyValuePair<ushort, object> pair)
        {
            if (!EnumExt.TryParse(pair.Key, out Grouping_FieldIndex enu))
            {
                throw new ArgumentException($"Unknown index: {pair.Key}");
            }
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                    obj.Nickname = (String)pair.Value;
                    break;
                case Grouping_FieldIndex.Mappings:
                    obj._Mappings.SetTo((IEnumerable<Mapping>)pair.Value);
                    break;
                default:
                    throw new ArgumentException($"Unknown enum type: {enu}");
            }
        }
    }
    #endregion

    #region Interface
    public partial interface IGrouping : IGroupingGetter, ILoquiClass<IGrouping, IGroupingGetter>, ILoquiClass<Grouping, IGroupingGetter>
    {
        new String Nickname { get; set; }

        new ISourceSetList<Mapping> Mappings { get; }
    }

    public partial interface IGroupingGetter : ILoquiObject
    {
        #region Nickname
        String Nickname { get; }

        #endregion
        #region Mappings
        IObservableSetList<Mapping> Mappings { get; }
        #endregion

    }

    #endregion

}

namespace BethesdaGitSync.Internals
{
    #region Field Index
    public enum Grouping_FieldIndex
    {
        Nickname = 0,
        Mappings = 1,
    }
    #endregion

    #region Registration
    public class Grouping_Registration : ILoquiRegistration
    {
        public static readonly Grouping_Registration Instance = new Grouping_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_BethesdaGitSync.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_BethesdaGitSync.ProtocolKey,
            msgID: 3,
            version: 0);

        public const string GUID = "2279225e-dc13-49bb-9308-840e9e53bdb6";

        public const ushort AdditionalFieldCount = 2;

        public const ushort FieldCount = 2;

        public static readonly Type MaskType = typeof(Grouping_Mask<>);

        public static readonly Type ErrorMaskType = typeof(Grouping_ErrorMask);

        public static readonly Type ClassType = typeof(Grouping);

        public static readonly Type GetterType = typeof(IGroupingGetter);

        public static readonly Type SetterType = typeof(IGrouping);

        public static readonly Type CommonType = typeof(GroupingCommon);

        public const string FullName = "BethesdaGitSync.Grouping";

        public const string Name = "Grouping";

        public const string Namespace = "BethesdaGitSync";

        public const byte GenericCount = 0;

        public static readonly Type GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "NICKNAME":
                    return (ushort)Grouping_FieldIndex.Nickname;
                case "MAPPINGS":
                    return (ushort)Grouping_FieldIndex.Mappings;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Mappings:
                    return true;
                case Grouping_FieldIndex.Nickname:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Mappings:
                    return true;
                case Grouping_FieldIndex.Nickname:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                case Grouping_FieldIndex.Mappings:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static string GetNthName(ushort index)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                    return "Nickname";
                case Grouping_FieldIndex.Mappings:
                    return "Mappings";
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                case Grouping_FieldIndex.Mappings:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsProtected(ushort index)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                case Grouping_FieldIndex.Mappings:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static Type GetNthType(ushort index)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                    return typeof(String);
                case Grouping_FieldIndex.Mappings:
                    return typeof(SourceSetList<Mapping>);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type ILoquiRegistration.CommonType => CommonType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Extensions
    public static partial class GroupingCommon
    {
        #region Copy Fields From
        public static void CopyFieldsFrom(
            IGrouping item,
            IGroupingGetter rhs,
            IGroupingGetter def,
            ErrorMaskBuilder errorMask,
            Grouping_CopyMask copyMask)
        {
            if (copyMask?.Nickname ?? true)
            {
                errorMask?.PushIndex((int)Grouping_FieldIndex.Nickname);
                try
                {
                    item.Nickname = rhs.Nickname;
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
            if (copyMask?.Mappings.Overall != CopyOption.Skip)
            {
                errorMask?.PushIndex((int)Grouping_FieldIndex.Mappings);
                try
                {
                    item.Mappings.SetToWithDefault(
                        rhs: rhs.Mappings,
                        def: def?.Mappings,
                        converter: (r, d) =>
                        {
                            switch (copyMask?.Mappings.Overall ?? CopyOption.Reference)
                            {
                                case CopyOption.Reference:
                                    return r;
                                case CopyOption.MakeCopy:
                                    return Mapping.Copy(
                                        r,
                                        copyMask?.Mappings?.Specific,
                                        def: d);
                                default:
                                    throw new NotImplementedException($"Unknown CopyOption {copyMask?.Mappings.Overall}. Cannot execute copy.");
                            }
                        }
                        );
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
        }

        #endregion

        public static void Clear(IGrouping item)
        {
            item.Nickname = default(String);
            item.Mappings.Unset();
        }

        public static Grouping_Mask<bool> GetEqualsMask(
            this IGroupingGetter item,
            IGroupingGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            var ret = new Grouping_Mask<bool>();
            FillEqualsMask(
                item: item,
                rhs: rhs,
                ret: ret,
                include: include);
            return ret;
        }

        public static void FillEqualsMask(
            IGroupingGetter item,
            IGroupingGetter rhs,
            Grouping_Mask<bool> ret,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            if (rhs == null) return;
            ret.Nickname = string.Equals(item.Nickname, rhs.Nickname);
            ret.Mappings = item.Mappings.CollectionEqualsHelper(
                rhs.Mappings,
                (loqLhs, loqRhs) => loqLhs.GetEqualsMask(loqRhs, include),
                include);
        }

        public static string ToString(
            this IGroupingGetter item,
            string name = null,
            Grouping_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            item.ToString(fg, name, printMask);
            return fg.ToString();
        }

        public static void ToString(
            this IGroupingGetter item,
            FileGeneration fg,
            string name = null,
            Grouping_Mask<bool> printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"{nameof(Grouping)} =>");
            }
            else
            {
                fg.AppendLine($"{name} ({nameof(Grouping)}) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Nickname ?? true)
                {
                    fg.AppendLine($"Nickname => {item.Nickname}");
                }
                if (printMask?.Mappings?.Overall ?? true)
                {
                    fg.AppendLine("Mappings =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        foreach (var subItem in item.Mappings)
                        {
                            fg.AppendLine("[");
                            using (new DepthWrapper(fg))
                            {
                                subItem?.ToString(fg, "Item");
                            }
                            fg.AppendLine("]");
                        }
                    }
                    fg.AppendLine("]");
                }
            }
            fg.AppendLine("]");
        }

        public static bool HasBeenSet(
            this IGroupingGetter item,
            Grouping_Mask<bool?> checkMask)
        {
            if (checkMask.Mappings.Overall.HasValue && checkMask.Mappings.Overall.Value != item.Mappings.HasBeenSet) return false;
            return true;
        }

        public static Grouping_Mask<bool> GetHasBeenSetMask(IGroupingGetter item)
        {
            var ret = new Grouping_Mask<bool>();
            ret.Nickname = true;
            ret.Mappings = new MaskItem<bool, IEnumerable<MaskItemIndexed<bool, Mapping_Mask<bool>>>>(item.Mappings.HasBeenSet, item.Mappings.WithIndex().Select((i) => new MaskItemIndexed<bool, Mapping_Mask<bool>>(i.Index, true, i.Item.GetHasBeenSetMask())));
            return ret;
        }

        #region Xml Translation
        #region Xml Write
        public static void Write_Xml(
            XElement node,
            IGroupingGetter item,
            bool doMasks,
            out Grouping_ErrorMask errorMask,
            Grouping_TranslationMask translationMask,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            Write_Xml(
                name: name,
                node: node,
                item: item,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Grouping_ErrorMask.Factory(errorMaskBuilder);
        }

        public static void Write_Xml(
            XElement node,
            IGroupingGetter item,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var elem = new XElement(name ?? "BethesdaGitSync.Grouping");
            node.Add(elem);
            if (name != null)
            {
                elem.SetAttributeValue("type", "BethesdaGitSync.Grouping");
            }
            WriteToNode_Xml(
                item: item,
                node: elem,
                errorMask: errorMask,
                translationMask: translationMask);
        }
        #endregion

        public static void WriteToNode_Xml(
            this IGroupingGetter item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            if ((translationMask?.GetShouldTranslate((int)Grouping_FieldIndex.Nickname) ?? true))
            {
                StringXmlTranslation.Instance.Write(
                    node: node,
                    name: nameof(item.Nickname),
                    item: item.Nickname,
                    fieldIndex: (int)Grouping_FieldIndex.Nickname,
                    errorMask: errorMask);
            }
            if ((translationMask?.GetShouldTranslate((int)Grouping_FieldIndex.Mappings) ?? true))
            {
                ListXmlTranslation<Mapping>.Instance.Write(
                    node: node,
                    name: nameof(item.Mappings),
                    item: item.Mappings,
                    fieldIndex: (int)Grouping_FieldIndex.Mappings,
                    errorMask: errorMask,
                    translationMask: translationMask?.GetSubCrystal((int)Grouping_FieldIndex.Mappings),
                    transl: (XElement subNode, Mapping subItem, ErrorMaskBuilder listSubMask, TranslationCrystal listTranslMask) =>
                    {
                        LoquiXmlTranslation<Mapping>.Instance.Write(
                            node: subNode,
                            item: subItem,
                            name: null,
                            errorMask: listSubMask,
                            translationMask: listTranslMask);
                    }
                    );
            }
        }

        public static void FillPublic_Xml(
            this Grouping item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            try
            {
                foreach (var elem in node.Elements())
                {
                    GroupingCommon.FillPublicElement_Xml(
                        item: item,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
        }

        public static void FillPublicElement_Xml(
            this Grouping item,
            XElement node,
            string name,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            switch (name)
            {
                case "Nickname":
                    if ((translationMask?.GetShouldTranslate((int)Grouping_FieldIndex.Nickname) ?? true))
                    {
                        try
                        {
                            errorMask?.PushIndex((int)Grouping_FieldIndex.Nickname);
                            if (StringXmlTranslation.Instance.Parse(
                                node: node,
                                item: out String NicknameParse,
                                errorMask: errorMask))
                            {
                                item.Nickname = NicknameParse;
                            }
                            else
                            {
                                item.Nickname = default(String);
                            }
                        }
                        catch (Exception ex)
                        when (errorMask != null)
                        {
                            errorMask.ReportException(ex);
                        }
                        finally
                        {
                            errorMask?.PopIndex();
                        }
                    }
                    break;
                case "Mappings":
                    if ((translationMask?.GetShouldTranslate((int)Grouping_FieldIndex.Mappings) ?? true))
                    {
                        try
                        {
                            errorMask?.PushIndex((int)Grouping_FieldIndex.Mappings);
                            if (ListXmlTranslation<Mapping>.Instance.Parse(
                                node: node,
                                enumer: out var MappingsItem,
                                transl: LoquiXmlTranslation<Mapping>.Instance.Parse,
                                errorMask: errorMask,
                                translationMask: translationMask))
                            {
                                item.Mappings.SetTo(MappingsItem);
                            }
                            else
                            {
                                item.Mappings.Unset();
                            }
                        }
                        catch (Exception ex)
                        when (errorMask != null)
                        {
                            errorMask.ReportException(ex);
                        }
                        finally
                        {
                            errorMask?.PopIndex();
                        }
                    }
                    break;
                default:
                    break;
            }
        }

        #endregion

    }
    #endregion

    #region Modules
    #region Mask
    public class Grouping_Mask<T> : IMask<T>, IEquatable<Grouping_Mask<T>>
    {
        #region Ctors
        public Grouping_Mask()
        {
        }

        public Grouping_Mask(T initialValue)
        {
            this.Nickname = initialValue;
            this.Mappings = new MaskItem<T, IEnumerable<MaskItemIndexed<T, Mapping_Mask<T>>>>(initialValue, null);
        }
        #endregion

        #region Members
        public T Nickname;
        public MaskItem<T, IEnumerable<MaskItemIndexed<T, Mapping_Mask<T>>>> Mappings;
        #endregion

        #region Equals
        public override bool Equals(object obj)
        {
            if (!(obj is Grouping_Mask<T> rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Grouping_Mask<T> rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(this.Nickname, rhs.Nickname)) return false;
            if (!object.Equals(this.Mappings, rhs.Mappings)) return false;
            return true;
        }
        public override int GetHashCode()
        {
            int ret = 0;
            ret = ret.CombineHashCode(this.Nickname?.GetHashCode());
            ret = ret.CombineHashCode(this.Mappings?.GetHashCode());
            return ret;
        }

        #endregion

        #region All Equal
        public bool AllEqual(Func<T, bool> eval)
        {
            if (!eval(this.Nickname)) return false;
            if (this.Mappings != null)
            {
                if (!eval(this.Mappings.Overall)) return false;
                if (this.Mappings.Specific != null)
                {
                    foreach (var item in this.Mappings.Specific)
                    {
                        if (!eval(item.Overall)) return false;
                        if (item.Specific != null && !item.Specific.AllEqual(eval)) return false;
                    }
                }
            }
            return true;
        }
        #endregion

        #region Translate
        public Grouping_Mask<R> Translate<R>(Func<T, R> eval)
        {
            var ret = new Grouping_Mask<R>();
            this.Translate_InternalFill(ret, eval);
            return ret;
        }

        protected void Translate_InternalFill<R>(Grouping_Mask<R> obj, Func<T, R> eval)
        {
            obj.Nickname = eval(this.Nickname);
            if (Mappings != null)
            {
                obj.Mappings = new MaskItem<R, IEnumerable<MaskItemIndexed<R, Mapping_Mask<R>>>>();
                obj.Mappings.Overall = eval(this.Mappings.Overall);
                if (Mappings.Specific != null)
                {
                    List<MaskItemIndexed<R, Mapping_Mask<R>>> l = new List<MaskItemIndexed<R, Mapping_Mask<R>>>();
                    obj.Mappings.Specific = l;
                    foreach (var item in Mappings.Specific.WithIndex())
                    {
                        MaskItemIndexed<R, Mapping_Mask<R>> mask = default;
                        mask.Index = item.Index;
                        if (item.Item != null)
                        {
                            mask = new MaskItemIndexed<R, Mapping_Mask<R>>(item.Item.Index);
                            mask.Overall = eval(item.Item.Overall);
                            if (item.Item.Specific != null)
                            {
                                mask.Specific = item.Item.Specific.Translate(eval);
                            }
                        }
                        l.Add(mask);
                    }
                }
            }
        }
        #endregion

        #region Clear Enumerables
        public void ClearEnumerables()
        {
            this.Mappings.Specific = null;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            return ToString(printMask: null);
        }

        public string ToString(Grouping_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(fg, printMask);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg, Grouping_Mask<bool> printMask = null)
        {
            fg.AppendLine($"{nameof(Grouping_Mask<T>)} =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Nickname ?? true)
                {
                    fg.AppendLine($"Nickname => {Nickname}");
                }
                if (printMask?.Mappings?.Overall ?? true)
                {
                    fg.AppendLine("Mappings =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        if (Mappings.Overall != null)
                        {
                            fg.AppendLine(Mappings.Overall.ToString());
                        }
                        if (Mappings.Specific != null)
                        {
                            foreach (var subItem in Mappings.Specific)
                            {
                                fg.AppendLine("[");
                                using (new DepthWrapper(fg))
                                {
                                    subItem?.ToString(fg);
                                }
                                fg.AppendLine("]");
                            }
                        }
                    }
                    fg.AppendLine("]");
                }
            }
            fg.AppendLine("]");
        }
        #endregion

    }

    public class Grouping_ErrorMask : IErrorMask, IErrorMask<Grouping_ErrorMask>
    {
        #region Members
        public Exception Overall { get; set; }
        private List<string> _warnings;
        public List<string> Warnings
        {
            get
            {
                if (_warnings == null)
                {
                    _warnings = new List<string>();
                }
                return _warnings;
            }
        }
        public Exception Nickname;
        public MaskItem<Exception, IEnumerable<MaskItem<Exception, Mapping_ErrorMask>>> Mappings;
        #endregion

        #region IErrorMask
        public object GetNthMask(int index)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                    return Nickname;
                case Grouping_FieldIndex.Mappings:
                    return Mappings;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthException(int index, Exception ex)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                    this.Nickname = ex;
                    break;
                case Grouping_FieldIndex.Mappings:
                    this.Mappings = new MaskItem<Exception, IEnumerable<MaskItem<Exception, Mapping_ErrorMask>>>(ex, null);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthMask(int index, object obj)
        {
            Grouping_FieldIndex enu = (Grouping_FieldIndex)index;
            switch (enu)
            {
                case Grouping_FieldIndex.Nickname:
                    this.Nickname = (Exception)obj;
                    break;
                case Grouping_FieldIndex.Mappings:
                    this.Mappings = (MaskItem<Exception, IEnumerable<MaskItem<Exception, Mapping_ErrorMask>>>)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public bool IsInError()
        {
            if (Overall != null) return true;
            if (Nickname != null) return true;
            if (Mappings != null) return true;
            return false;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            var fg = new FileGeneration();
            ToString(fg);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg)
        {
            fg.AppendLine("Grouping_ErrorMask =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (this.Overall != null)
                {
                    fg.AppendLine("Overall =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendLine($"{this.Overall}");
                    }
                    fg.AppendLine("]");
                }
                ToString_FillInternal(fg);
            }
            fg.AppendLine("]");
        }
        protected void ToString_FillInternal(FileGeneration fg)
        {
            fg.AppendLine($"Nickname => {Nickname}");
            fg.AppendLine("Mappings =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (Mappings.Overall != null)
                {
                    fg.AppendLine(Mappings.Overall.ToString());
                }
                if (Mappings.Specific != null)
                {
                    foreach (var subItem in Mappings.Specific)
                    {
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            subItem?.ToString(fg);
                        }
                        fg.AppendLine("]");
                    }
                }
            }
            fg.AppendLine("]");
        }
        #endregion

        #region Combine
        public Grouping_ErrorMask Combine(Grouping_ErrorMask rhs)
        {
            var ret = new Grouping_ErrorMask();
            ret.Nickname = this.Nickname.Combine(rhs.Nickname);
            ret.Mappings = new MaskItem<Exception, IEnumerable<MaskItem<Exception, Mapping_ErrorMask>>>(this.Mappings.Overall.Combine(rhs.Mappings.Overall), new List<MaskItem<Exception, Mapping_ErrorMask>>(this.Mappings.Specific.And(rhs.Mappings.Specific)));
            return ret;
        }
        public static Grouping_ErrorMask Combine(Grouping_ErrorMask lhs, Grouping_ErrorMask rhs)
        {
            if (lhs != null && rhs != null) return lhs.Combine(rhs);
            return lhs ?? rhs;
        }
        #endregion

        #region Factory
        public static Grouping_ErrorMask Factory(ErrorMaskBuilder errorMask)
        {
            if (errorMask?.Empty ?? true) return null;
            return new Grouping_ErrorMask();
        }
        #endregion

    }
    public class Grouping_CopyMask
    {
        public Grouping_CopyMask()
        {
        }

        public Grouping_CopyMask(bool defaultOn, CopyOption deepCopyOption = CopyOption.Reference)
        {
            this.Nickname = defaultOn;
            this.Mappings = new MaskItem<CopyOption, Mapping_CopyMask>(deepCopyOption, default);
        }

        #region Members
        public bool Nickname;
        public MaskItem<CopyOption, Mapping_CopyMask> Mappings;
        #endregion

    }

    public class Grouping_TranslationMask : ITranslationMask
    {
        #region Members
        private TranslationCrystal _crystal;
        public bool Nickname;
        public MaskItem<bool, Mapping_TranslationMask> Mappings;
        #endregion

        #region Ctors
        public Grouping_TranslationMask()
        {
        }

        public Grouping_TranslationMask(bool defaultOn)
        {
            this.Nickname = defaultOn;
            this.Mappings = new MaskItem<bool, Mapping_TranslationMask>(defaultOn, null);
        }

        #endregion

        public TranslationCrystal GetCrystal()
        {
            if (_crystal != null) return _crystal;
            List<(bool On, TranslationCrystal SubCrystal)> ret = new List<(bool On, TranslationCrystal SubCrystal)>();
            GetCrystal(ret);
            _crystal = new TranslationCrystal()
            {
                Crystal = ret.ToArray()
            };
            return _crystal;
        }

        protected void GetCrystal(List<(bool On, TranslationCrystal SubCrystal)> ret)
        {
            ret.Add((Nickname, null));
            ret.Add((Mappings?.Overall ?? true, Mappings?.Specific?.GetCrystal()));
        }
    }
    #endregion

    #endregion

}
