/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Noggog;
using Noggog.Notifying;
using BethesdaGitSync.Internals;
using ReactiveUI;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;
using Loqui.Internal;
using System.Diagnostics;
using System.Collections.Specialized;

namespace BethesdaGitSync
{
    #region Class
    public partial class Mapping : 
        LoquiNotifyingObject,
        IMapping,
        ILoquiObject<Mapping>,
        ILoquiObjectSetter,
        IEquatable<Mapping>
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => Mapping_Registration.Instance;
        public static Mapping_Registration Registration => Mapping_Registration.Instance;

        #region Ctor
        public Mapping()
        {
            _hasBeenSetTracker = new BitArray(((ILoquiObject)this).Registration.FieldCount);
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region BinaryPath
        public bool BinaryPath_IsSet
        {
            get => _hasBeenSetTracker[(int)Mapping_FieldIndex.BinaryPath];
            set => this.RaiseAndSetIfChanged(_hasBeenSetTracker, value, (int)Mapping_FieldIndex.BinaryPath, nameof(BinaryPath_IsSet));
        }
        bool IMappingGetter.BinaryPath_IsSet => BinaryPath_IsSet;
        private FilePath _BinaryPath;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        public FilePath BinaryPath
        {
            get => this._BinaryPath;
            set => BinaryPath_Set(value);
        }
        FilePath IMappingGetter.BinaryPath => this.BinaryPath;
        public void BinaryPath_Set(
            FilePath value,
            bool markSet = true)
        {
            this.RaiseAndSetIfChanged(ref _BinaryPath, value, _hasBeenSetTracker, markSet, (int)Mapping_FieldIndex.BinaryPath, nameof(BinaryPath), nameof(BinaryPath_IsSet));
        }
        public void BinaryPath_Unset()
        {
            this.BinaryPath_Set(default(FilePath), false);
        }
        #endregion
        #region FolderPath
        public bool FolderPath_IsSet
        {
            get => _hasBeenSetTracker[(int)Mapping_FieldIndex.FolderPath];
            set => this.RaiseAndSetIfChanged(_hasBeenSetTracker, value, (int)Mapping_FieldIndex.FolderPath, nameof(FolderPath_IsSet));
        }
        bool IMappingGetter.FolderPath_IsSet => FolderPath_IsSet;
        private DirectoryPath _FolderPath;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        public DirectoryPath FolderPath
        {
            get => this._FolderPath;
            set => FolderPath_Set(value);
        }
        DirectoryPath IMappingGetter.FolderPath => this.FolderPath;
        public void FolderPath_Set(
            DirectoryPath value,
            bool markSet = true)
        {
            this.RaiseAndSetIfChanged(ref _FolderPath, value, _hasBeenSetTracker, markSet, (int)Mapping_FieldIndex.FolderPath, nameof(FolderPath), nameof(FolderPath_IsSet));
        }
        public void FolderPath_Unset()
        {
            this.FolderPath_Set(default(DirectoryPath), false);
        }
        #endregion

        #region Loqui Getter Interface

        protected object GetNthObject(ushort index) => MappingCommon.GetNthObject(index, this);
        object ILoquiObjectGetter.GetNthObject(ushort index) => this.GetNthObject(index);

        protected bool GetNthObjectHasBeenSet(ushort index) => MappingCommon.GetNthObjectHasBeenSet(index, this);
        bool ILoquiObjectGetter.GetNthObjectHasBeenSet(ushort index) => this.GetNthObjectHasBeenSet(index);

        protected void UnsetNthObject(ushort index, NotifyingUnsetParameters cmds) => MappingCommon.UnsetNthObject(index, this, cmds);
        void ILoquiObjectSetter.UnsetNthObject(ushort index, NotifyingUnsetParameters cmds) => this.UnsetNthObject(index, cmds);

        #endregion

        #region Loqui Interface
        protected void SetNthObjectHasBeenSet(ushort index, bool on)
        {
            MappingCommon.SetNthObjectHasBeenSet(index, on, this);
        }
        void ILoquiObjectSetter.SetNthObjectHasBeenSet(ushort index, bool on) => this.SetNthObjectHasBeenSet(index, on);

        #endregion

        IMask<bool> IEqualsMask<Mapping>.GetEqualsMask(Mapping rhs, EqualsMaskHelper.Include include) => MappingCommon.GetEqualsMask(this, rhs, include);
        IMask<bool> IEqualsMask<IMappingGetter>.GetEqualsMask(IMappingGetter rhs, EqualsMaskHelper.Include include) => MappingCommon.GetEqualsMask(this, rhs, include);
        #region To String
        public override string ToString()
        {
            return MappingCommon.ToString(this, printMask: null);
        }

        public string ToString(
            string name = null,
            Mapping_Mask<bool> printMask = null)
        {
            return MappingCommon.ToString(this, name: name, printMask: printMask);
        }

        public void ToString(
            FileGeneration fg,
            string name = null)
        {
            MappingCommon.ToString(this, fg, name: name, printMask: null);
        }

        #endregion

        IMask<bool> ILoquiObjectGetter.GetHasBeenSetMask() => this.GetHasBeenSetMask();
        public Mapping_Mask<bool> GetHasBeenSetMask()
        {
            return MappingCommon.GetHasBeenSetMask(this);
        }
        #region Equals and Hash
        public override bool Equals(object obj)
        {
            if (!(obj is Mapping rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Mapping rhs)
        {
            if (rhs == null) return false;
            if (BinaryPath_IsSet != rhs.BinaryPath_IsSet) return false;
            if (BinaryPath_IsSet)
            {
                if (!object.Equals(this.BinaryPath, rhs.BinaryPath)) return false;
            }
            if (FolderPath_IsSet != rhs.FolderPath_IsSet) return false;
            if (FolderPath_IsSet)
            {
                if (!object.Equals(this.FolderPath, rhs.FolderPath)) return false;
            }
            return true;
        }

        public override int GetHashCode()
        {
            int ret = 0;
            if (BinaryPath_IsSet)
            {
                ret = HashHelper.GetHashCode(BinaryPath).CombineHashCode(ret);
            }
            if (FolderPath_IsSet)
            {
                ret = HashHelper.GetHashCode(FolderPath).CombineHashCode(ret);
            }
            return ret;
        }

        #endregion


        #region Xml Translation
        #region Xml Create
        [DebuggerStepThrough]
        public static Mapping Create_Xml(
            XElement node,
            Mapping_TranslationMask translationMask = null)
        {
            return Create_Xml(
                node: node,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        [DebuggerStepThrough]
        public static Mapping Create_Xml(
            XElement node,
            out Mapping_ErrorMask errorMask,
            bool doMasks = true,
            Mapping_TranslationMask translationMask = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            var ret = Create_Xml(
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask.GetCrystal());
            errorMask = Mapping_ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }

        public static Mapping Create_Xml(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            var ret = new Mapping();
            try
            {
                foreach (var elem in node.Elements())
                {
                    MappingCommon.FillPublicElement_Xml(
                        item: ret,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            return ret;
        }

        public static Mapping Create_Xml(
            string path,
            Mapping_TranslationMask translationMask = null)
        {
            var node = XDocument.Load(path).Root;
            return Create_Xml(
                node: node,
                translationMask: translationMask);
        }

        public static Mapping Create_Xml(
            string path,
            out Mapping_ErrorMask errorMask,
            Mapping_TranslationMask translationMask = null)
        {
            var node = XDocument.Load(path).Root;
            return Create_Xml(
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static Mapping Create_Xml(
            string path,
            ErrorMaskBuilder errorMask,
            Mapping_TranslationMask translationMask = null)
        {
            var node = XDocument.Load(path).Root;
            return Create_Xml(
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        public static Mapping Create_Xml(
            Stream stream,
            Mapping_TranslationMask translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            return Create_Xml(
                node: node,
                translationMask: translationMask);
        }

        public static Mapping Create_Xml(
            Stream stream,
            out Mapping_ErrorMask errorMask,
            Mapping_TranslationMask translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            return Create_Xml(
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static Mapping Create_Xml(
            Stream stream,
            ErrorMaskBuilder errorMask,
            Mapping_TranslationMask translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            return Create_Xml(
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        #endregion

        #region Xml Copy In
        public void CopyIn_Xml(
            XElement node,
            NotifyingFireParameters cmds = null)
        {
            CopyIn_Xml_Internal(
                node: node,
                errorMask: null,
                translationMask: null,
                cmds: cmds);
        }

        public virtual void CopyIn_Xml(
            XElement node,
            out Mapping_ErrorMask errorMask,
            Mapping_TranslationMask translationMask = null,
            bool doMasks = true,
            NotifyingFireParameters cmds = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            CopyIn_Xml_Internal(
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal(),
                cmds: cmds);
            errorMask = Mapping_ErrorMask.Factory(errorMaskBuilder);
        }

        protected void CopyIn_Xml_Internal(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            NotifyingFireParameters cmds = null)
        {
            LoquiXmlTranslation<Mapping>.Instance.CopyIn(
                node: node,
                item: this,
                skipProtected: true,
                errorMask: errorMask,
                translationMask: translationMask,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            string path,
            NotifyingFireParameters cmds = null)
        {
            var node = XDocument.Load(path).Root;
            this.CopyIn_Xml(
                node: node,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            string path,
            out Mapping_ErrorMask errorMask,
            Mapping_TranslationMask translationMask,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var node = XDocument.Load(path).Root;
            this.CopyIn_Xml(
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask,
                cmds: cmds,
                doMasks: doMasks);
        }

        public void CopyIn_Xml(
            Stream stream,
            NotifyingFireParameters cmds = null)
        {
            var node = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                node: node,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            Stream stream,
            out Mapping_ErrorMask errorMask,
            Mapping_TranslationMask translationMask,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var node = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask,
                cmds: cmds,
                doMasks: doMasks);
        }

        #endregion

        #region Xml Write
        public virtual void Write_Xml(
            XElement node,
            out Mapping_ErrorMask errorMask,
            bool doMasks = true,
            Mapping_TranslationMask translationMask = null,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            this.Write_Xml(
                name: name,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Mapping_ErrorMask.Factory(errorMaskBuilder);
        }

        public virtual void Write_Xml(
            string path,
            out Mapping_ErrorMask errorMask,
            Mapping_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }

        public void Write_Xml(
            string path,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }
        public virtual void Write_Xml(
            Stream stream,
            out Mapping_ErrorMask errorMask,
            Mapping_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }

        public void Write_Xml(
            Stream stream,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }
        public void Write_Xml(
            XElement node,
            string name = null,
            Mapping_TranslationMask translationMask = null)
        {
            this.Write_Xml(
                name: name,
                node: node,
                errorMask: null,
                translationMask: translationMask.GetCrystal());
        }

        public void Write_Xml(
            string path,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().SaveIfChanged(path);
        }

        public void Write_Xml(
            Stream stream,
            string name = null)
        {
            var node = new XElement("topnode");
            Write_Xml(
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().Save(stream);
        }

        public void Write_Xml(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            MappingCommon.Write_Xml(
                item: this,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }
        #endregion

        #endregion

        protected readonly BitArray _hasBeenSetTracker;
        protected bool GetHasBeenSet(int index)
        {
            switch ((Mapping_FieldIndex)index)
            {
                case Mapping_FieldIndex.BinaryPath:
                case Mapping_FieldIndex.FolderPath:
                    return _hasBeenSetTracker[index];
                default:
                    throw new ArgumentException($"Unknown field index: {index}");
            }
        }

        public Mapping Copy(
            Mapping_CopyMask copyMask = null,
            IMappingGetter def = null)
        {
            return Mapping.Copy(
                this,
                copyMask: copyMask,
                def: def);
        }

        public static Mapping Copy(
            IMapping item,
            Mapping_CopyMask copyMask = null,
            IMappingGetter def = null)
        {
            Mapping ret;
            if (item.GetType().Equals(typeof(Mapping)))
            {
                ret = new Mapping();
            }
            else
            {
                ret = (Mapping)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public static Mapping Copy_ToLoqui(
            IMappingGetter item,
            Mapping_CopyMask copyMask = null,
            IMappingGetter def = null)
        {
            Mapping ret;
            if (item.GetType().Equals(typeof(Mapping)))
            {
                ret = new Mapping() as Mapping;
            }
            else
            {
                ret = (Mapping)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public void CopyFieldsFrom(
            IMappingGetter rhs,
            NotifyingFireParameters cmds = null)
        {
            this.CopyFieldsFrom(
                rhs: (IMappingGetter)rhs,
                def: null,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: null,
                cmds: cmds);
        }

        public void CopyFieldsFrom(
            IMappingGetter rhs,
            Mapping_CopyMask copyMask,
            IMappingGetter def = null,
            NotifyingFireParameters cmds = null)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: def,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        public void CopyFieldsFrom(
            IMappingGetter rhs,
            out Mapping_ErrorMask errorMask,
            Mapping_CopyMask copyMask = null,
            IMappingGetter def = null,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            MappingCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMaskBuilder,
                copyMask: copyMask,
                cmds: cmds);
            errorMask = Mapping_ErrorMask.Factory(errorMaskBuilder);
        }

        public void CopyFieldsFrom(
            IMappingGetter rhs,
            ErrorMaskBuilder errorMask,
            Mapping_CopyMask copyMask = null,
            IMappingGetter def = null,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            MappingCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        void ILoquiObjectSetter.SetNthObject(ushort index, object obj, NotifyingFireParameters cmds) => this.SetNthObject(index, obj, cmds);
        protected void SetNthObject(ushort index, object obj, NotifyingFireParameters cmds = null)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    this.BinaryPath = (FilePath)obj;
                    break;
                case Mapping_FieldIndex.FolderPath:
                    this.FolderPath = (DirectoryPath)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        partial void ClearPartial(NotifyingUnsetParameters cmds);

        protected void CallClearPartial_Internal(NotifyingUnsetParameters cmds)
        {
            ClearPartial(cmds);
        }

        public void Clear(NotifyingUnsetParameters cmds = null)
        {
            CallClearPartial_Internal(cmds);
            MappingCommon.Clear(this, cmds);
        }


        public static Mapping Create(IEnumerable<KeyValuePair<ushort, object>> fields)
        {
            var ret = new Mapping();
            foreach (var pair in fields)
            {
                CopyInInternal_Mapping(ret, pair);
            }
            return ret;
        }

        protected static void CopyInInternal_Mapping(Mapping obj, KeyValuePair<ushort, object> pair)
        {
            if (!EnumExt.TryParse(pair.Key, out Mapping_FieldIndex enu))
            {
                throw new ArgumentException($"Unknown index: {pair.Key}");
            }
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    obj.BinaryPath = (FilePath)pair.Value;
                    break;
                case Mapping_FieldIndex.FolderPath:
                    obj.FolderPath = (DirectoryPath)pair.Value;
                    break;
                default:
                    throw new ArgumentException($"Unknown enum type: {enu}");
            }
        }
        public static void CopyIn(IEnumerable<KeyValuePair<ushort, object>> fields, Mapping obj)
        {
            ILoquiObjectExt.CopyFieldsIn(obj, fields, def: null, skipProtected: false, cmds: null);
        }

    }
    #endregion

    #region Interface
    public partial interface IMapping : IMappingGetter, ILoquiClass<IMapping, IMappingGetter>, ILoquiClass<Mapping, IMappingGetter>
    {
        new FilePath BinaryPath { get; set; }
        new bool BinaryPath_IsSet { get; set; }
        void BinaryPath_Set(FilePath item, bool hasBeenSet = true);
        void BinaryPath_Unset();

        new DirectoryPath FolderPath { get; set; }
        new bool FolderPath_IsSet { get; set; }
        void FolderPath_Set(DirectoryPath item, bool hasBeenSet = true);
        void FolderPath_Unset();

    }

    public partial interface IMappingGetter : ILoquiObject
    {
        #region BinaryPath
        FilePath BinaryPath { get; }
        bool BinaryPath_IsSet { get; }

        #endregion
        #region FolderPath
        DirectoryPath FolderPath { get; }
        bool FolderPath_IsSet { get; }

        #endregion

    }

    #endregion

}

namespace BethesdaGitSync.Internals
{
    #region Field Index
    public enum Mapping_FieldIndex
    {
        BinaryPath = 0,
        FolderPath = 1,
    }
    #endregion

    #region Registration
    public class Mapping_Registration : ILoquiRegistration
    {
        public static readonly Mapping_Registration Instance = new Mapping_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_GitConverter.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_GitConverter.ProtocolKey,
            msgID: 2,
            version: 0);

        public const string GUID = "15afffaa-eeaa-40c5-b515-ca20a34e4b76";

        public const ushort AdditionalFieldCount = 2;

        public const ushort FieldCount = 2;

        public static readonly Type MaskType = typeof(Mapping_Mask<>);

        public static readonly Type ErrorMaskType = typeof(Mapping_ErrorMask);

        public static readonly Type ClassType = typeof(Mapping);

        public static readonly Type GetterType = typeof(IMappingGetter);

        public static readonly Type SetterType = typeof(IMapping);

        public static readonly Type CommonType = typeof(MappingCommon);

        public const string FullName = "BethesdaGitSync.Mapping";

        public const string Name = "Mapping";

        public const string Namespace = "BethesdaGitSync";

        public const byte GenericCount = 0;

        public static readonly Type GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "BINARYPATH":
                    return (ushort)Mapping_FieldIndex.BinaryPath;
                case "FOLDERPATH":
                    return (ushort)Mapping_FieldIndex.FolderPath;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                case Mapping_FieldIndex.FolderPath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                case Mapping_FieldIndex.FolderPath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                case Mapping_FieldIndex.FolderPath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static string GetNthName(ushort index)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    return "BinaryPath";
                case Mapping_FieldIndex.FolderPath:
                    return "FolderPath";
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                case Mapping_FieldIndex.FolderPath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsProtected(ushort index)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                case Mapping_FieldIndex.FolderPath:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static Type GetNthType(ushort index)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    return typeof(FilePath);
                case Mapping_FieldIndex.FolderPath:
                    return typeof(DirectoryPath);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type ILoquiRegistration.CommonType => CommonType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Extensions
    public static partial class MappingCommon
    {
        #region Copy Fields From
        public static void CopyFieldsFrom(
            IMapping item,
            IMappingGetter rhs,
            IMappingGetter def,
            ErrorMaskBuilder errorMask,
            Mapping_CopyMask copyMask,
            NotifyingFireParameters cmds = null)
        {
            if (copyMask?.BinaryPath ?? true)
            {
                errorMask?.PushIndex((int)Mapping_FieldIndex.BinaryPath);
                try
                {
                    if (LoquiHelper.DefaultSwitch(
                        rhsItem: rhs.BinaryPath,
                        rhsHasBeenSet: rhs.BinaryPath_IsSet,
                        defItem: def?.BinaryPath ?? default(FilePath),
                        defHasBeenSet: def?.BinaryPath_IsSet ?? false,
                        outRhsItem: out var rhsBinaryPathItem,
                        outDefItem: out var defBinaryPathItem))
                    {
                        item.BinaryPath = rhsBinaryPathItem;
                    }
                    else
                    {
                        item.BinaryPath_Unset();
                    }
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
            if (copyMask?.FolderPath ?? true)
            {
                errorMask?.PushIndex((int)Mapping_FieldIndex.FolderPath);
                try
                {
                    if (LoquiHelper.DefaultSwitch(
                        rhsItem: rhs.FolderPath,
                        rhsHasBeenSet: rhs.FolderPath_IsSet,
                        defItem: def?.FolderPath ?? default(DirectoryPath),
                        defHasBeenSet: def?.FolderPath_IsSet ?? false,
                        outRhsItem: out var rhsFolderPathItem,
                        outDefItem: out var defFolderPathItem))
                    {
                        item.FolderPath = rhsFolderPathItem;
                    }
                    else
                    {
                        item.FolderPath_Unset();
                    }
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
        }

        #endregion

        public static void SetNthObjectHasBeenSet(
            ushort index,
            bool on,
            IMapping obj,
            NotifyingFireParameters cmds = null)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    obj.BinaryPath_IsSet = on;
                    break;
                case Mapping_FieldIndex.FolderPath:
                    obj.FolderPath_IsSet = on;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void UnsetNthObject(
            ushort index,
            IMapping obj,
            NotifyingUnsetParameters cmds = null)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    obj.BinaryPath_Unset();
                    break;
                case Mapping_FieldIndex.FolderPath:
                    obj.FolderPath_Unset();
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthObjectHasBeenSet(
            ushort index,
            IMapping obj)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    return obj.BinaryPath_IsSet;
                case Mapping_FieldIndex.FolderPath:
                    return obj.FolderPath_IsSet;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static object GetNthObject(
            ushort index,
            IMappingGetter obj)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    return obj.BinaryPath;
                case Mapping_FieldIndex.FolderPath:
                    return obj.FolderPath;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void Clear(
            IMapping item,
            NotifyingUnsetParameters cmds = null)
        {
            item.BinaryPath_Unset();
            item.FolderPath_Unset();
        }

        public static Mapping_Mask<bool> GetEqualsMask(
            this IMappingGetter item,
            IMappingGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            var ret = new Mapping_Mask<bool>();
            FillEqualsMask(
                item: item,
                rhs: rhs,
                ret: ret,
                include: include);
            return ret;
        }

        public static void FillEqualsMask(
            IMappingGetter item,
            IMappingGetter rhs,
            Mapping_Mask<bool> ret,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            if (rhs == null) return;
            ret.BinaryPath = item.BinaryPath_IsSet == rhs.BinaryPath_IsSet && object.Equals(item.BinaryPath, rhs.BinaryPath);
            ret.FolderPath = item.FolderPath_IsSet == rhs.FolderPath_IsSet && object.Equals(item.FolderPath, rhs.FolderPath);
        }

        public static string ToString(
            this IMappingGetter item,
            string name = null,
            Mapping_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            item.ToString(fg, name, printMask);
            return fg.ToString();
        }

        public static void ToString(
            this IMappingGetter item,
            FileGeneration fg,
            string name = null,
            Mapping_Mask<bool> printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"{nameof(Mapping)} =>");
            }
            else
            {
                fg.AppendLine($"{name} ({nameof(Mapping)}) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.BinaryPath ?? true)
                {
                    fg.AppendLine($"BinaryPath => {item.BinaryPath}");
                }
                if (printMask?.FolderPath ?? true)
                {
                    fg.AppendLine($"FolderPath => {item.FolderPath}");
                }
            }
            fg.AppendLine("]");
        }

        public static bool HasBeenSet(
            this IMappingGetter item,
            Mapping_Mask<bool?> checkMask)
        {
            if (checkMask.BinaryPath.HasValue && checkMask.BinaryPath.Value != item.BinaryPath_IsSet) return false;
            if (checkMask.FolderPath.HasValue && checkMask.FolderPath.Value != item.FolderPath_IsSet) return false;
            return true;
        }

        public static Mapping_Mask<bool> GetHasBeenSetMask(IMappingGetter item)
        {
            var ret = new Mapping_Mask<bool>();
            ret.BinaryPath = item.BinaryPath_IsSet;
            ret.FolderPath = item.FolderPath_IsSet;
            return ret;
        }

        #region Xml Translation
        #region Xml Write
        public static void Write_Xml(
            XElement node,
            IMappingGetter item,
            bool doMasks,
            out Mapping_ErrorMask errorMask,
            Mapping_TranslationMask translationMask,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            Write_Xml(
                name: name,
                node: node,
                item: item,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Mapping_ErrorMask.Factory(errorMaskBuilder);
        }

        public static void Write_Xml(
            XElement node,
            IMappingGetter item,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var elem = new XElement(name ?? "BethesdaGitSync.Mapping");
            node.Add(elem);
            if (name != null)
            {
                elem.SetAttributeValue("type", "BethesdaGitSync.Mapping");
            }
            WriteToNode_Xml(
                item: item,
                node: elem,
                errorMask: errorMask,
                translationMask: translationMask);
        }
        #endregion

        public static void WriteToNode_Xml(
            this IMappingGetter item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            if (item.BinaryPath_IsSet
                && (translationMask?.GetShouldTranslate((int)Mapping_FieldIndex.BinaryPath) ?? true))
            {
                FilePathXmlTranslation.Instance.Write(
                    node: node,
                    name: nameof(item.BinaryPath),
                    item: item.BinaryPath,
                    fieldIndex: (int)Mapping_FieldIndex.BinaryPath,
                    errorMask: errorMask);
            }
            if (item.FolderPath_IsSet
                && (translationMask?.GetShouldTranslate((int)Mapping_FieldIndex.FolderPath) ?? true))
            {
                DirectoryPathXmlTranslation.Instance.Write(
                    node: node,
                    name: nameof(item.FolderPath),
                    item: item.FolderPath,
                    fieldIndex: (int)Mapping_FieldIndex.FolderPath,
                    errorMask: errorMask);
            }
        }

        public static void FillPublic_Xml(
            this Mapping item,
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            try
            {
                foreach (var elem in node.Elements())
                {
                    MappingCommon.FillPublicElement_Xml(
                        item: item,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
        }

        public static void FillPublicElement_Xml(
            this Mapping item,
            XElement node,
            string name,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            switch (name)
            {
                case "BinaryPath":
                    try
                    {
                        errorMask?.PushIndex((int)Mapping_FieldIndex.BinaryPath);
                        if (FilePathXmlTranslation.Instance.Parse(
                            node: node,
                            item: out FilePath BinaryPathParse,
                            errorMask: errorMask))
                        {
                            item.BinaryPath = BinaryPathParse;
                        }
                        else
                        {
                            item.BinaryPath = default(FilePath);
                        }
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                case "FolderPath":
                    try
                    {
                        errorMask?.PushIndex((int)Mapping_FieldIndex.FolderPath);
                        if (DirectoryPathXmlTranslation.Instance.Parse(
                            node: node,
                            item: out DirectoryPath FolderPathParse,
                            errorMask: errorMask))
                        {
                            item.FolderPath = FolderPathParse;
                        }
                        else
                        {
                            item.FolderPath = default(DirectoryPath);
                        }
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                default:
                    break;
            }
        }

        #endregion

    }
    #endregion

    #region Modules
    #region Mask
    public class Mapping_Mask<T> : IMask<T>, IEquatable<Mapping_Mask<T>>
    {
        #region Ctors
        public Mapping_Mask()
        {
        }

        public Mapping_Mask(T initialValue)
        {
            this.BinaryPath = initialValue;
            this.FolderPath = initialValue;
        }
        #endregion

        #region Members
        public T BinaryPath;
        public T FolderPath;
        #endregion

        #region Equals
        public override bool Equals(object obj)
        {
            if (!(obj is Mapping_Mask<T> rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Mapping_Mask<T> rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(this.BinaryPath, rhs.BinaryPath)) return false;
            if (!object.Equals(this.FolderPath, rhs.FolderPath)) return false;
            return true;
        }
        public override int GetHashCode()
        {
            int ret = 0;
            ret = ret.CombineHashCode(this.BinaryPath?.GetHashCode());
            ret = ret.CombineHashCode(this.FolderPath?.GetHashCode());
            return ret;
        }

        #endregion

        #region All Equal
        public bool AllEqual(Func<T, bool> eval)
        {
            if (!eval(this.BinaryPath)) return false;
            if (!eval(this.FolderPath)) return false;
            return true;
        }
        #endregion

        #region Translate
        public Mapping_Mask<R> Translate<R>(Func<T, R> eval)
        {
            var ret = new Mapping_Mask<R>();
            this.Translate_InternalFill(ret, eval);
            return ret;
        }

        protected void Translate_InternalFill<R>(Mapping_Mask<R> obj, Func<T, R> eval)
        {
            obj.BinaryPath = eval(this.BinaryPath);
            obj.FolderPath = eval(this.FolderPath);
        }
        #endregion

        #region Clear Enumerables
        public void ClearEnumerables()
        {
        }
        #endregion

        #region To String
        public override string ToString()
        {
            return ToString(printMask: null);
        }

        public string ToString(Mapping_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(fg, printMask);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg, Mapping_Mask<bool> printMask = null)
        {
            fg.AppendLine($"{nameof(Mapping_Mask<T>)} =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.BinaryPath ?? true)
                {
                    fg.AppendLine($"BinaryPath => {BinaryPath}");
                }
                if (printMask?.FolderPath ?? true)
                {
                    fg.AppendLine($"FolderPath => {FolderPath}");
                }
            }
            fg.AppendLine("]");
        }
        #endregion

    }

    public class Mapping_ErrorMask : IErrorMask, IErrorMask<Mapping_ErrorMask>
    {
        #region Members
        public Exception Overall { get; set; }
        private List<string> _warnings;
        public List<string> Warnings
        {
            get
            {
                if (_warnings == null)
                {
                    _warnings = new List<string>();
                }
                return _warnings;
            }
        }
        public Exception BinaryPath;
        public Exception FolderPath;
        #endregion

        #region IErrorMask
        public object GetNthMask(int index)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    return BinaryPath;
                case Mapping_FieldIndex.FolderPath:
                    return FolderPath;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthException(int index, Exception ex)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    this.BinaryPath = ex;
                    break;
                case Mapping_FieldIndex.FolderPath:
                    this.FolderPath = ex;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthMask(int index, object obj)
        {
            Mapping_FieldIndex enu = (Mapping_FieldIndex)index;
            switch (enu)
            {
                case Mapping_FieldIndex.BinaryPath:
                    this.BinaryPath = (Exception)obj;
                    break;
                case Mapping_FieldIndex.FolderPath:
                    this.FolderPath = (Exception)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public bool IsInError()
        {
            if (Overall != null) return true;
            if (BinaryPath != null) return true;
            if (FolderPath != null) return true;
            return false;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            var fg = new FileGeneration();
            ToString(fg);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg)
        {
            fg.AppendLine("Mapping_ErrorMask =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (this.Overall != null)
                {
                    fg.AppendLine("Overall =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendLine($"{this.Overall}");
                    }
                    fg.AppendLine("]");
                }
                ToString_FillInternal(fg);
            }
            fg.AppendLine("]");
        }
        protected void ToString_FillInternal(FileGeneration fg)
        {
            fg.AppendLine($"BinaryPath => {BinaryPath}");
            fg.AppendLine($"FolderPath => {FolderPath}");
        }
        #endregion

        #region Combine
        public Mapping_ErrorMask Combine(Mapping_ErrorMask rhs)
        {
            var ret = new Mapping_ErrorMask();
            ret.BinaryPath = this.BinaryPath.Combine(rhs.BinaryPath);
            ret.FolderPath = this.FolderPath.Combine(rhs.FolderPath);
            return ret;
        }
        public static Mapping_ErrorMask Combine(Mapping_ErrorMask lhs, Mapping_ErrorMask rhs)
        {
            if (lhs != null && rhs != null) return lhs.Combine(rhs);
            return lhs ?? rhs;
        }
        #endregion

        #region Factory
        public static Mapping_ErrorMask Factory(ErrorMaskBuilder errorMask)
        {
            if (errorMask?.Empty ?? true) return null;
            return new Mapping_ErrorMask();
        }
        #endregion

    }
    public class Mapping_CopyMask
    {
        public Mapping_CopyMask()
        {
        }

        public Mapping_CopyMask(bool defaultOn, CopyOption deepCopyOption = CopyOption.Reference)
        {
            this.BinaryPath = defaultOn;
            this.FolderPath = defaultOn;
        }

        #region Members
        public bool BinaryPath;
        public bool FolderPath;
        #endregion

    }

    public class Mapping_TranslationMask : ITranslationMask
    {
        #region Members
        private TranslationCrystal _crystal;
        public bool BinaryPath;
        public bool FolderPath;
        #endregion

        #region Ctors
        public Mapping_TranslationMask()
        {
        }

        public Mapping_TranslationMask(bool defaultOn)
        {
            this.BinaryPath = defaultOn;
            this.FolderPath = defaultOn;
        }

        #endregion

        public TranslationCrystal GetCrystal()
        {
            if (_crystal != null) return _crystal;
            List<(bool On, TranslationCrystal SubCrystal)> ret = new List<(bool On, TranslationCrystal SubCrystal)>();
            GetCrystal(ret);
            _crystal = new TranslationCrystal()
            {
                Crystal = ret.ToArray()
            };
            return _crystal;
        }

        protected void GetCrystal(List<(bool On, TranslationCrystal SubCrystal)> ret)
        {
            ret.Add((BinaryPath, null));
            ret.Add((FolderPath, null));
        }
    }
    #endregion

    #endregion

}
